name: "Terraform Plan & Deploy"
on:
  push:
    branches: ["main"]
    paths:
      - Azure/**
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Extract-TFVars"
        run: |
          git fetch origin --prune --unshallow
          LAST_COMMIT=$(git rev-parse HEAD^1)
          CHANGED_FILES=$(git diff --name-only $LAST_COMMIT $CI_COMMIT_SHA | grep "Azure")
          FOLDER_PATH=$(dirname "$CHANGED_FILES" | head -n 1)
          cd $FOLDER_PATH
          TFVARS_FILE=$(find "$FOLDER_PATH" -type f -name '*.tfvars' -print -quit)
          echo $CHANGED_FILES and $FOLDER_PATH and $TFVARS_FILE
          echo FOLDER_PATH=$FOLDER_PATH >> $GITHUB_ENV
          echo TFVARS_FILE=$TFVARS_FILE >> $GITHUB_ENV
     

      - name: "Terraform Init"
        run: |
          cd $FOLDER_PATH
          terraform init
      
      - name: "Terraform Validate"
        run: |
          cd $FOLDER_PATH
          pwd
          terraform validate

      - name: "Terraform Plan"
        run: |
          cd $FOLDER_PATH
          terraform plan -var-file=$TFVARS_FILE

    #   - name: "Terraform Apply"
    #     run: teraform apply -var-file=$TFVARS_FILE -auto-approve
