name: "Terraform Plan & Deploy"
on:
  push:
    branches: ["main"]
    paths:
      - Azure/**
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Extract-TFVars"
        run: |
          git fetch origin --prune --unshallow
          LAST_COMMIT=$(git rev-parse HEAD^1)
          CHANGED_FILES=$(git diff --name-only $LAST_COMMIT $CI_COMMIT_SHA | grep "Azure")
          FOLDER_PATH=$(dirname "$CHANGED_FILES" | head -n 1)
          TFVARS_FILE=$(basename $(find "$FOLDER_PATH" -type f -name '*.tfvars' -print -quit))
          echo FOLDER_PATH=$FOLDER_PATH >> $GITHUB_ENV
          echo TFVARS_FILE=$TFVARS_FILE >> $GITHUB_ENV
     
      - name: "Terraform Init"
        id: init
        run: |
          cd $FOLDER_PATH
          terraform init
      
      - name: "Terraform Validate"
        id: validate
        run: |
          cd $FOLDER_PATH
          terraform validate

      - name: "Terraform Plan"
        id: plan
        if: steps.validate.outcome == 'success'
        run: |
          cd $FOLDER_PATH
          terraform plan -var-file=$TFVARS_FILE

      - name: "Terraform Apply"
        id: apply
        if: steps.plan.outcome == 'success'
        run: | 
          cd $FOLDER_PATH
          teraform apply -var-file=$TFVARS_FILE -auto-approve
