name: "Terraform Plan & Deploy"
on:
  push:
    branches: ["main"]
    paths:
      - Azure/**
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Terraform Format"
        run: terraform fmt -check

      - name: "Terraform Init"
        run: terraform init

      - name: "Extract TFVars"
        run: |
          git fetch origin --prune --unshallow
          git checkout $GITHUB_SHA -- Azure/**/*.tfvars
          export TFVARS_FILE=$(find Azure/ -name "*.tfvars")
          echo $TFVARS_FILE

      - name: "Terraform Plan"
        run: terraform plan -var-file=$TFVARS_FILE

      - name: "Terraform Apply"
        run: teraform apply -var-file=$TFVARS_FILE -auto-approve
