name: "Terraform Plan & Deploy"
on:
  push:
    branches: ["main"]
    paths:
      - Azure/**
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Terraform Format"
        run: terraform fmt -check

      - name: "Terraform Init"
        run: terraform init

      - name: "Extract-TFVars"
        id: tfvars
        run: |
          git fetch origin --prune --unshallow
          LAST_COMMIT=$(git rev-parse HEAD^1)
          TFVARS_FILE=$(git diff --name-only $LAST_COMMIT $CI_COMMIT_SHA | grep ".tfvars")
          FOLDER_PATH=$(dirname "$TFVARS_FILE" | head -n 1)
          echo TFVARS_FILE=$TFVARS_FILE >> $GITHUB_ENV

      - name: "Terraform Plan"
        run: |
          echo $TFVARS_FILE
          terraform plan -var-file=$TFVARS_FILE

    #   - name: "Terraform Apply"
    #     run: teraform apply -var-file=$TFVARS_FILE -auto-approve
